app.py
from flask import Flask, render_template, request
from common.database import Database
from main.routes import main

app = Flask(__name__)

app.register_blueprint(main)

@app.before_first_request
def db():
    Database.initialize()



main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from bson.objectid import ObjectId
from common.database import Database

# File for storing my routes!

# Cretaing blueprint
main = Blueprint("main", __name__)

# Creating my basic route for returning all of the previous data I typed! 
@main.route("/")
def index():
    todos = Database.find({})
    return render_template("home.html", todos = todos)

# Route for adding infromation I type!
@main.route("/add_todo", methods = ["POST"])
def add_todo():
    # Gettin that item!
    todo_item = request.form.get("add-todo")
    
    # Storing into my db!
    json = {"add": todo_item, "complete": False}
    Database.insert(data = json)
    return redirect(url_for("main.index"))

# Route for marking the completed ones!
@main.route("/complete_todo/<oid>")
def complete_todo(oid):
    # Finding the item by ObjectId!
    todo_item = Database.find_one({"_id": ObjectId(oid)})
    item = todo_item["add"]
    # Creating my own json with same data except now complete is equal to true!
    json = {
        "_id": ObjectId(oid),
        "add": item,
        "complete": True
    }
    # Repalcing new json with the existing one!
    Database.replace_one(todo_item, json)
    return redirect(url_for("main.index"))

# Delete data with value true off complete!
@main.route("/delete_completed")
def delete_completed():
    Database.remove({"complete": True})
    return redirect(url_for("main.index"))

# deleting all items!
@main.route("/delete_all")
def delete_all():
    Database.remove({})
    return redirect(url_for("main.index"))

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <h3>WHAT DO YOU NEED TO DO TODAY?</h3>
        <form action = "{{ url_for('main.add_todo') }}" method = "POST" role = "form"> <input type="text" name = "add-todo" placeholder="Type some information!" autocomplete="off">
            <button class="btn1" type="submit">ADD</button>
            <div class="div">
                <a href = "{{ url_for('main.delete_completed') }}" class="btn2" type="submit">DELETE COMPLETED</a>
                <a href= "{{ url_for('main.delete_all') }}" class="btn2" type="submit">DELETE ALL</a>
            </div>
            <div class="div_link">
            {% for todo in todos %}
                <a href="{{ url_for('main.complete_todo', oid = todo._id) }}">
                    <p class="content {% if todo.complete %} todo-completed {% endif %}">{{ todo.add }}</p>
                </a>
            {% endfor %}
            </form>
            </div>
        </div>
        

    </div>
    <footer>Copyright © 2021 Frano Penava</footer>

</body>

</html>